### ISSUE TITLE
 The function ”huygns_integration“   is missing

### ISSUE THREAD

**Issue by Tang-Douer** [oriolrios/PhDThesis#1]

**Comment by oriolrios** [comment]
Hello Tang-Douer. I've uploaded the missing version of the file. Sorry. Cheers

**Comment by Tang-Douer** [comment]
Thank you very much, Dr. Rios. But I'm sorry to trouble you again, the function "F" is missing in line 17 of the script "huygns_integration.m"  you just uploaded. I think this should be the Richards equation referred to in your paper. I apologize for being so late in replying to you because I rarely log in to GitHub.
![image](https://user-images.githubusercontent.com/85384003/132000895-cb0e5d0c-1899-4218-9191-50fae49e8921.png)
